name: self_driving_car
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - pip
    - python
    - pyqt
    - tensorflow
    - keras
    - pip:
          - numpy
          - matplotlib
          - jupyter
          - pillow
          - scikit-learn
          - scikit-image
          - scipy
          - h5py
          - eventlet
          - flask-socketio
          - seaborn
          - pandas
          - ffmpeg
          - imageio
          - moviepy
          - opencv-python
          - requests
